# Generated by Django 4.0.6 on 2022-08-05 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderoulette', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nickname',
            new_name='name',
        ),
    ]
